name: .NET

on:
  push:
    branches: [ nuget ]
  pull_request:
    branches: [ nuget ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore src/LimFx.Common
    - name: Build
      run: dotnet build src/LimFx.Common --no-restore
    - name: Pack
      run: dotnet pack src/LimFx.Common
    - name: Publish NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
          PROJECT_FILE_PATH: src/LimFx.Common/LimFx.Common.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
